Fixes for Package Validation Suite Errors
Unity-Technologies/com.unity.ads.ios-support pull request #8
Opened 2020-09-08 21:41 UTC by UnitySteven

Fix Package Version
Update SkAdNetworks file to use url approach with v2 links
Fix asmdefs

2020-09-08 22:03 UTC, richardh-unity3d approved these changes

2020-09-08 22:10 UTC, richardh-unity3d requested changes

2020-09-08 22:10 UTC, richardh-unity3d commented on TestProject~/2019.4/Assets/Plugins/SkAdNetworks
> +https://skan.mz.unity3d.com/v2/partner/skadnetworks.plist.xml
The name of this file should be `SKAdNetworks`

https://github.com/Unity-Technologies/SKADID

https://github.com/Unity-Technologies/com.unity.ads.ios-support/blob/master/com.unity.ads.ios-support/Editor/PostProcessBuildPlist.cs#L46

2020-09-08 22:55 UTC, richardh-unity3d approved these changes

2020-09-09 00:25 UTC, bzarzoza approved these changes

2020-09-09 00:25 UTC, merged